import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
    version: 1,
    tables: [
        tableSchema({
            name: 'events_store',
            columns: [
                { name: 'aggregate_id', type: 'string' },
                { name: 'aggregate_type', type: 'string' },
                { name: 'event_type', type: 'string' },
                { name: 'event_data', type: 'string' },
                { name: 'event_timestamp_at', type: 'number' },
                { name: 'version', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'snapshots',
            columns: [
                { name: 'aggregate_id', type: 'string' },
                { name: 'aggregate_type', type: 'string' },
                { name: 'snapshot_data', type: 'string' },
                { name: 'snapshot_timestamp_at', type: 'number' },
                { name: 'version', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_accounts',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'type', type: 'string' },
                { name: 'currency_code', type: 'string' },
                { name: 'initial_balance', type: 'number' },
                { name: 'current_balance', type: 'number' },
                { name: 'emoji', type: 'string', isOptional: true },
                { name: 'color', type: 'string' },
                { name: 'is_active', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_categories',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'icon', type: 'string', isOptional: true },
                { name: 'color', type: 'string' },
                { name: 'type', type: 'string' },
                { name: 'parent_category_id', type: 'string', isOptional: true },
                { name: 'is_system', type: 'boolean' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_transactions',
            columns: [
                { name: 'account_id', type: 'string', isIndexed: true },
                { name: 'category_id', type: 'string', isOptional: true },
                { name: 'amount', type: 'number' },
                { name: 'type', type: 'string' },
                { name: 'date_at', type: 'number' },
                { name: 'description', type: 'string', isOptional: true },
                { name: 'is_recurring', type: 'boolean' },
                { name: 'transfer_id', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_transfers',
            columns: [
                { name: 'from_account_id', type: 'string' },
                { name: 'to_account_id', type: 'string' },
                { name: 'amount', type: 'number' },
                { name: 'date_at', type: 'number' },
                { name: 'description', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'tags',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'emoji', type: 'string', isOptional: true },
                { name: 'color', type: 'string' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_transaction_tags',
            columns: [
                { name: 'transaction_id', type: 'string', isIndexed: true },
                { name: 'tag_id', type: 'string', isIndexed: true },
            ],
        }),
        tableSchema({
            name: 'personal_budgets',
            columns: [
                { name: 'category_id', type: 'string', isOptional: true },
                { name: 'account_id', type: 'string', isOptional: true },
                { name: 'amount', type: 'number' },
                { name: 'period', type: 'string' },
                { name: 'start_date_at', type: 'number' },
                { name: 'end_date_at', type: 'number' },
                { name: 'alert_threshold', type: 'number' },
                { name: 'spent_amount', type: 'number' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_challenges',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'target_amount', type: 'number' },
                { name: 'start_date_at', type: 'number' },
                { name: 'end_date_at', type: 'number' },
                { name: 'current_amount', type: 'number' },
                { name: 'is_completed', type: 'boolean' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'settings',
            columns: [
                { name: 'default_currency', type: 'string' },
                { name: 'theme', type: 'string' },
                { name: 'security_pin_hash', type: 'string', isOptional: true },
                { name: 'is_biometrics_enabled', type: 'boolean' },
                { name: 'is_stealth_mode', type: 'boolean' },
                { name: 'backup_frequency', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_auto_category_rules',
            columns: [
                { name: 'category_id', type: 'string' },
                { name: 'keyword', type: 'string' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_subscriptions',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'amount', type: 'number' },
                { name: 'due_date_at', type: 'number' },
                { name: 'recurrence', type: 'string' },
                { name: 'category_id', type: 'string', isOptional: true },
                { name: 'account_id', type: 'string', isOptional: true },
                { name: 'is_active', type: 'boolean' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'exchange_rates',
            columns: [
                { name: 'from_currency', type: 'string' },
                { name: 'to_currency', type: 'string' },
                { name: 'rate', type: 'number' },
                { name: 'date_at', type: 'number' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_connected_banks',
            columns: [
                { name: 'bank_name', type: 'string' },
                { name: 'account_number', type: 'string', isOptional: true },
                { name: 'access_token', type: 'string', isOptional: true },
                { name: 'last_sync_at', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_recurring_payments',
            columns: [
                { name: 'account_id', type: 'string' },
                { name: 'category_id', type: 'string', isOptional: true },
                { name: 'amount', type: 'number' },
                { name: 'type', type: 'string' },
                { name: 'description', type: 'string', isOptional: true },
                { name: 'recurrence', type: 'string' },
                { name: 'due_date_at', type: 'number' },
                { name: 'is_active', type: 'boolean' },
                { name: 'created_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'personal_achievements',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'condition', type: 'string' },
                { name: 'is_unlocked', type: 'boolean' },
                { name: 'unlocked_date_at', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number' },
            ],
        }),
    ],
});
